version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.0  # Specify the Python version
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install Flask
      - pip install pytest
      - pip install pytest-pythonpath
      - pip install requests
      - pip install python-dotenv
      - pip install gunicorn
      - pip install pyinstaller

  pre_build:
    commands:
      - echo Running tests...
      - pytest currency-converter/tests/ || { echo 'Tests failed'; exit 1; }  # Run all tests in the tests/ directory

  build:
    commands:
      - echo Building the application...
      - pyinstaller --onefile --noconsole currency-converter/app.py || { echo 'Build failed'; exit 1; }  # Create a standalone executable

  post_build:
    commands:
      - echo Renaming the output file...
      - mv dist/app dist/app.exe  # Rename the file to include an extension
      - echo Listing files in dist directory...
      - ls dist/

artifacts:
  files:
    - app.exe  # Use the renamed file
    - '**/*'  # This will include all files and directories recursively
  base-directory: dist  # Specify the base directory where the artifact is located
  discard-paths: no
